name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
            toolchain: nightly
    - name: Build
      run: rustup install nightly && cargo build --verbose
    - name: Run tests
      run: rustup install nightly && cargo test --verbose
